#Anchor definition with &


on:
  push:
    paths: &frontend_paths
      - “src/frontend/**”
      - "yarn.lock"
    
  pull_request:
    paths: *frontend_paths


jobs:
  test:
    runs-on: ubuntu-latest
    strategy: &my_strategy
      matrix:
        node-version: [16, 18, 20]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - &setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
  
  build:
    runs-on: ubuntu-latest
    strategy: *my_strategy
    steps:
      - *setup-node